### ISSUE TITLE
(discuss) on including public keys in events

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-ethereum#106]
### Problem
https://github.com/hoprnet/hopr-ethereum/issues/106#issuecomment-669308644

### potential solutions
- overwrite 2 bits at topic 0
- event includes only half of the uncompressed public key (indexed) and the other half in data

**Comment by nionis** [comment]
@SCBuergel please update the issue with the issue we are trying to fix / advantages of including pubKeys in the event

**Comment by SCBuergel** [comment]
### Problem
When sending a HOPR packet, the node needs to know the HOPR addresses (pub keys) of the intermediate nodes and the recipient to assemble the Sphinx header. OTOH, the limiting factor of available routes is the availability of open payment channels between nodes. Thus, in order to establish a route, a node needs to consume the topology of the payment layer (which node has an open payment channel to which other node). In addition, this information needs to be mapped onto HOPR address so that the sender can establish the packet.

### Example
Assume the following trivial topology of established payment channels (`---`, `\`, `/` lines indicated open payment channels):

```
Seb --- Steven --- Rob
   \                 \
    ------ Rich --- Jose --- Rik
               \             /
               Peter -------
```

In this example assume that `Seb` wants to establish a route to `Rik`, a [routing algorithm](https://en.wikipedia.org/wiki/A*_search_algorithm) needs to find a valid route (if any is possible). By consuming event data from the HOPR payment channel smart contract, it finds one (out of several) valid routes:
`Seb -> Steven -> Robert -> Jose -> Rik`

After finding that this route is possible, the routing algorithm also needs to pass the HOPR addresses (pub keys) to the module that generates the Sphinx packet.

@robertkiel pls extend / correct as necessary.

**Comment by robertkiel** [comment]
@nionis, @SCBuergel 

Let's distinguish two problems:

1. the concrete routing algorithm. There are a few options - graph theory has been a topic since a few centuries. Right, in my opinion we should do an A*-flavored approach or just the good old Dijkstra.

2. the way we get informed about edges in the network graph. (This is how we generate the input for the algorithm, and it is independent from the choice which which algorithm we use.)

Before we start over, note that there are some constraints:
- we cannot `query` any public resource as querying reveals what we are searching for - we could do that anyway but this would be far away from being efficient in any way, see [Path ORAM](https://eprint.iacr.org/2013/280.pdf) for a potential solution
- we therefor have to `listen` and do some data mining on the data that we get
- on-chain space is very scarce, so we have keep the data that we store per channel resp. per account as minimal as possible
- space in a transaction is also scarce, so we have to keep our signatures clean and drop any unnecessary data.

 Due to the two last points, we should not use raw public keys as they require two words of storage in either the `calldata` or in `storage`. Therefore we use only compressed public keys since off-chain decompression is way cheaper than on-chain decompression resp. storing raw public keys on-chain.

@nionis The question is now where we store that the 257th bit of the public key. We could use topic0 or the data section. I favor topic0 as this allows us to search for a specific event for example immediately after submitting the opening / settlement transaction. Having the public key in the data section will require filtering multiple events which should in my opinion be done by `geth` and not by `hopr`

**Comment by SCBuergel** [comment]
Great input!

> 1. the concrete routing algorithm. There are a few options - graph theory has been a topic since a few centuries. Right now, in my opinion we should implement an A*-flavored approach or just the good old Dijkstra.

Absolutely, maybe let's keep this in some way easily extendable. I can imagine people building their own routing algorithm. We - building the very first version of the protocol - shouldn't try to win routing efficiency contests here but rather provide the foundation that others can extended and modify. At the same time, this extendability should not take a massive hit on efficiency though.

> Due to the two last points, we should not use raw public keys as they require two words of storage in either the `calldata` or in `storage`. Therefore we use only compressed public keys since off-chain decompression is way cheaper than on-chain decompression resp. storing raw public keys on-chain.

Anything that we could store or compute off-chain, should *always* be kept off-chain. But sometimes improvements of e.g. minimizing on-chain storage require more computation on-chain that end up being more expensive overall. So before we make unusual adjustments (like manually squeezing two data fields into one word), tightly packing calldata field, let's make a test to see what we really gain.

Lastly there's a readability vs efficiency trade-off, e.g. online assembly. Application layer logic on permissionless decentralized public ledgers should be geared towards retail auditability. I.e. if I need to have 3 years+ experience in writing YUL assembly, then this isn't a great piece of trustless code in practice. As an order of magnitude rule of thumb: if not
> 
> @nionis The question is now where we store that the 257th bit of the public key. We could use topic0 or the data section. I favor topic0 as this allows us to search for a specific event for example immediately after submitting the opening / settlement transaction. Having the public key in the data section will require filtering multiple events which should in my opinion be done by `geth` and not by `hopr`

**Comment by robertkiel** [comment]
> Lastly there's a readability vs efficiency trade-off, e.g. online assembly. Application layer logic on permissionless decentralized public ledgers should be geared towards retail auditability. I.e. if I need to have 3 years+ experience in writing YUL assembly, then this isn't a great piece of trustless code in practice. As an order of magnitude rule of thumb: I'd only make something less readable (by e.g. using inline assembly) if it saves in average (remember: e.g. writing into storage is highly non-constant cost) over 1k gas.

For that reason, I don't use any non-standard calldata encoding as it saves less than 1k gas. In contrast to that, storing compressed instead uncompressed public keys saves at least 5k gas.

**Comment by robertkiel** [comment]
I've checked web3.js and TheGraph - they both support custom topic0s, see [TheGraph](https://thegraph.com/docs/define-a-subgraph#anonymous-events) and [Web3.js](https://web3js.readthedocs.io/en/v1.2.7/web3-eth-subscribe.html#id16)

**Comment by nionis** [comment]
I believe at the end of the day it all boils down on how much we care about overwriting those 2 bits as it makes listening to our events a little bit unconventional. This can be greatly helped by making the [getTopic0](https://github.com/hoprnet/hopr-core-ethereum/commit/7d7213391d96b1f07f20ef8a6775e4b6109eea6e#diff-f09e22bcc41713ed8cf0d53a65d87203R481) function part of `hopr-utils` and of course adding documentation.

@robertkiel I would like to better understand [this function](https://github.com/hoprnet/hopr-core-ethereum/commit/7d7213391d96b1f07f20ef8a6775e4b6109eea6e#diff-f09e22bcc41713ed8cf0d53a65d87203R481), it seems to me that it will always return 4 strings, as @SCBuergel mentioned:
> Can't we leave that bit out and just guess it or fix it to 0...?

We don't have to index those bits, we already index the first half of the public key, so that should be enough.

**Comment by robertkiel** [comment]
@nionis That's a little bit advanced usage of Ethereum / Web3.js. 

First of all, event subscriptions work with so-called [Bloom Filter](https://en.wikipedia.org/wiki/Bloom_filter). TLDR: membership check is cheap but there are false positives. So, when we create a subscription, we populate a query for a bloom filter.

Attaching the same listener to two different events is done like this. We create a subscription like the one below:
`topic0: [ keccak('Event0(...args)'), keccak('Event1(...args)')]`
`topicN: [ potentialValueOfFirstIndexedArgEvent0, anotherpotentialValueOfFirstIndexedArgEvent0, potentialValueOfFirstIndexedArgEvent1]`

Any found event will have `topic0` set to either `keccak('Event0(...args)')` or `keccak('Event1(...args)')`. Same principle applies for the following topics.

**Comment by nionis** [comment]
thanks everybody for the input, since we moved into the `topic0` direction I will be closing the issue
